# Generated by Django 4.2.5 on 2023-09-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_donor_address_donor_gender_alter_donor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dntn_date', models.DateField()),
                ('donor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodapp.donor')),
            ],
        ),
    ]
