# Generated by Django 4.2.5 on 2023-10-06 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodtype', models.CharField(max_length=5, verbose_name='Blood type')),
                ('units_in_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation_Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=50, verbose_name='Donation center')),
                ('location', models.CharField(blank=True, default='N/A', max_length=50, null=True, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('recipient_name', models.CharField(max_length=50, verbose_name='Recipient name')),
                ('bloodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodapp.bloodtype')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bloodapp.donation_center'),
            preserve_default=False,
        ),
    ]
